In [1]:
import numpy as np

In [54]:
A = np.array([[0, 2, 0, 3],
              [2, 0, 4, 6],
              [0, 4, 0, 1],
              [3, 6, 1, 0]])

W = np.zeros(A.shape)
for i, row in enumerate(A):
    W[i][i] = np.sum(row)
    
P = np.linalg.inv(W)@A
P

array([[0.        , 0.4       , 0.        , 0.6       ],
       [0.16666667, 0.        , 0.33333333, 0.5       ],
       [0.        , 0.8       , 0.        , 0.2       ],
       [0.3       , 0.6       , 0.1       , 0.        ]])

In [49]:
P = A.copy()
# print (P)
for i, row in enumerate(P):
#     print (row)
    print (row/np.sum(row))
P

[0.  0.4 0.  0.6]
[0.16666667 0.         0.33333333 0.5       ]
[0.  0.8 0.  0.2]
[0.3 0.6 0.1 0. ]


array([[0, 2, 0, 3],
       [2, 0, 4, 6],
       [0, 4, 0, 1],
       [3, 6, 1, 0]])

In [58]:
T = 4
X = np.array([1/A.shape[0] for _ in range(A.shape[0])])
X = np.array([0, 0, 1, 0])
print (X)
X@np.power(P, T)


[0 0 1 0]


array([0.    , 0.4096, 0.    , 0.0016])